name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  three_dart:
    path: ../
  three_dart_jsm:
    path: ../../three_dart_jsm/
  # three_dart:
  #   git:
  #     url: 'https://github.com/Knightro63/three_dart.git'
  # three_dart_jsm: 
  #   git:
  #     url: 'https://github.com/Knightro63/three_dart_jsm.git'
  # universal_ui: ^0.0.8
  flutter_gl: ^0.0.21

dependency_overrides:
  # three_dart:
  #   path: ../
  # three_dart_jsm:
  #   path: ../../three_dart_jsm/
#   flutter_gl:
#     path: ../../flutter_gl/flutter_gl


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  
flutter:
  uses-material-design: true
  assets:
    # - assets/helvetiker_bold.typeface.json
    - assets/pingfang.ttf
    - assets/kenpixel.ttf
    - assets/winter.jpg
    - assets/lut.cube
    - assets/demo.png
    - assets/KOMO-v5.cube
    - assets/screenshots/
    - assets/models/obj/male02/
    - assets/models/json/
    - assets/models/gltf/
    - assets/models/gltf/test/
    - assets/models/gltf/RobotExpressive/
    - assets/models/gltf/DamagedHelmet/glTF/
    - assets/models/gltf/AnimatedMorphSphere/glTF/
    - assets/models/svg/
    - assets/models/fbx/
    - assets/textures/
    - assets/textures/equirectangular/
    - assets/textures/terrain/
    - assets/textures/patterns/
    - assets/textures/sprites/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
