name: three_dart
description: three.js implement by Dart. Dart 3D library. an easy to use, lightweight, cross-platform, general purpose 3D library. 
version: 0.0.17
homepage: https://github.com/wasabia/three_dart

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  universal_html: ^2.0.8
  ffi: ^2.0.1
  image: ^4.0.02
  flutter_gl: ^0.0.21
  crypto: ^3.0.1
  meta:
  
  # flutter_webgpu:
  #   path: ../flutter_webgpu

dependency_overrides:
  # three_dart_jsm:
  #   path: ../three_dart_jsm
  # flutter_gl:
  #   path: ../flutter_gl/flutter_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

# The following section is specific to Flutter.
flutter:

